name: Docker Publish

on:
  push:
    branches: [ master ]

jobs:

  tobysbot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@v1.13.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.6.2
      with:
        images: ghcr.io/TobyMeehan/tobysbot

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        file: ./TobysBot.Discord/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
