# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]  

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Authentication File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: Authentication.json
        FILE_DATA: ${{ secrets.AUTHENTICATION }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build
      run: npm run build
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: build
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/
    - name: Publish with FTP
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{ secrets.FTP_SERVER }}
        # FTP user
        user: ${{ secrets.FTP_ACCOUNT_USERNAME }}
        # FTP password
        password: ${{ secrets.FTP_ACCOUNT_PASSWORD }}
        # Force SSL encryption
        forceSsl: false
        # Local directory
        localDir: ./build
        # Remote directory
        remoteDir: /bot
    - name: HTTP Request Action
      # You may pin to the exact commit or the version.
      # uses: fjogeleit/http-request-action@3634ea0063747172ea475d8dafb6596eab2a1e11
      uses: fjogeleit/http-request-action@v1.4.1
      with:
        # Request URL
        url: https://bot.tobymeehan.com
        # Request Method
        method: GET
        # Content Type
        # contentType: # optional, default is application/json
        # Request Body as JSON String
        # data: # optional, default is {} 
        # Auth Username
        # username: # optional
        # Auth Password
        # password: # optional
        # Request Timeout in Sec
        # timeout: # optional, default is 5000
        # Bearer Authentication Token
        # bearerToken: # optional
        # Custom HTTP Headers
        # customHeaders: # optional
        # Prevent this Action to fail if the request respond without an response
        preventFailureOnNoResponse: true
