# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]  

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Create Authentication File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: Authentication.json
        FILE_DATA: ${{ secrets.AUTHENTICATION }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: build
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/
      
  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Build
      uses: actions/download-artifact@v2
      with:
        # Artifact name
        name: build
        # Destination path
        path: ./build
    - name: Publish with FTP
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{ secrets.FTP_SERVER }}
        # FTP user
        user: ${{ secrets.FTP_ACCOUNT_USERNAME }}
        # FTP password
        password: ${{ secrets.FTP_ACCOUNT_PASSWORD }}
        # Force SSL encryption
        forceSsl: false
        # Local directory
        localDir: ./build
        # Remote directory
        remoteDir: /bot
      
