# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm build
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        ftp-server: ${{ secrets.FTP_SERVER }}
        # FTP account username
        ftp-username: ${{ secrets.FTP_ACCOUNT_USERNAME }}
        # FTP account password
        ftp-password: ${{ secrets.FTP_ACCOUNT_PASSWORD }}
        # The local folder to copy, defaults to root project folder
        local-dir: ./build
        # Passes through options into git-ftp
        #git-ftp-args: # optional
      
